# Blog settings
permalink: date


# My variables
name: Matherantics
description: Mathematical rants and computer nerdiness
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge

gems:
 - jekyll-feed

# Tags
tag_page: '/tag.html'
